[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "unitree-sdk2py"
version = "0.1"
requires-python = "~= 3.10"
dynamic = [
    "description",
    "readme",
    "license",
    "authors",
    # "dependencies",
    "urls",
]
dependencies = [
    "cyclonedds==0.10.2", # as said in docs. Should also work with 0.10.5
    "numpy",
    "opencv-python",
    "pygame",
    "ultralytics",
    "torch==2.9.0",
    "pandas",
    "tqdm",
    "seaborn",
    # "go2_webrtc_driver",
]
